baseURL = 'https://cornish.app/'
languageCode = 'en-us'
title = 'Cornish Learn'

[params]

[taxonomies]
	author = "authors"
	category = "categories"

[outputFormats]
    [outputFormats.manifest]
        name = "manifest"
        baseName = "manifest"
        mediaType = "application/json"
        notAlternative = "true"


[outputs]
    home = [ "HTML", "RSS", "MANIFEST"]

[menu]
  [[menu.main]]
    name = 'Home'
    pre = ''
    url = '/home/'
    weight = 1
 [menu.main.params]
   class='home-outline'

  [[menu.main]]
    name = 'Posts'
    pre = ''
    url = '/posts/'
    weight = 2
  [menu.main.params]
   class='cube-outline'

[[menu.main]]
  name = 'News'
  pre = ''
  url = '/bbcnews/'
   weight = 3
  [menu.main.params]
   class='chatbubble-ellipses-outline'

[[menu.main]]
  name = 'FAQ'
  pre = ''
  url = '/faq/'
   weight = 4
   [menu.main.params]
   class='layers-outline'

[[menu.main]]
  name = 'Settings'
  post = 'menu-settings'
  icon = 'menu-outline'
  pre = 'menu-settings'
  url = "#sidebarPanel"
   weight = 5
[menu.main.params]
   class='menu-outline'
   
